# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awaard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_rates', to='awaard.Project'),
        ),
        migrations.AlterField(
            model_name='designrate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_rates', to='awaard.Project'),
        ),
        migrations.AlterField(
            model_name='usabilityrate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usability_rates', to='awaard.Project'),
        ),
    ]
