# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-01 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awaard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='awaard.Profile'),
        ),
    ]
