# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaard', '0002_auto_20190701_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
